### ISSUE TITLE
ln -s path_to_unzipped_Linemod_preprocessed ffb6d/dataset/linemod/

### ISSUE THREAD

**Issue by Darrenxc** [zhujunli1993/SwinDePose#3]
when i downloaded linemod_preprocessed dataset, and built environment from you docker image, i wonder where is the path ffb6d/dataset/linemod/     is this the path i need to makdir?

**Comment by henryhskim** [comment]
I am also curious about this. Did you figure this out?

**Comment by fedona** [comment]
I am also curious about this
