### ISSUE TITLE
About LM-O dataset

### ISSUE THREAD

**Issue by weidu3** [zhujunli1993/SwinDePose#4]
Hello, sorry to bother you again. I now have two questions: 
   1. I refer to previous work, such as pvn3d and ffb6d, they did not do any training on the LM-O dataset, they just trained with LM and only tested on LM-O. I see that you provided the training code on LM-O, I wonder if this compares fairly with the previous work?
   2. I found that the egg carton in the LM-O dataset was pressed by a red car, just like the picture below. So I'm curious, the eggbox is tested on the LM-O dataset, does it use the original data of LM-O?
![0012](https://github.com/zhujunli1993/SwinDePose/assets/101306990/72ba8a96-4cf1-4c47-9d8e-2ea46b57a34d)

**Comment by zhujunli1993** [comment]
Our method was tested in the same dataset as PVN3D and FFB6D use, which is a fair comparison. For LM-O training, we used the BOP challenge dataset of LM-O.

**Comment by weidu3** [comment]
> Our method was tested in the same dataset as PVN3D and FFB6D use, which is a fair comparison. For LM-O training, we used the BOP challenge dataset of LM-O. 

1.Isn't the BOP challenge dataset of LM-O used in FFB6D？
2.Are there still two different LMO datasets? 
I hope to hear from you.

**Comment by zhujunli1993** [comment]
> 

1. Yes. They used BOP challenge dataset of Occ-LM in FFB6D.
2.  BOP provides a training set of O-LM. For testing sets, both the original LM-O and BOP version LM-O are the same.
