### ISSUE TITLE
About GT Mask

### ISSUE THREAD

**Issue by GalenOOO** [zhujunli1993/SwinDePose#5]
Thanks for your good work and sharing codes. In your paper, you displayed the test results with and without GT mask. My question is that since your pipeline predicts 3D keypoints and segmentation at the same time rather than first predicting mask then localizing the 3D keypoints, what's the difference between with/without GT mask?

**Comment by zhujunli1993** [comment]
During testing, either the predicted mask or the ground truth mask is used in the pose estimation process.

**Comment by GalenOOO** [comment]
Thanks for your reply. So you use predicted mask or the GT mask to control the points voting for the keypoints of certain object. Different mask leads to different points, thus leading to different pose results?

**Comment by zhujunli1993** [comment]
Yes.
